[project]
name = "shieldcraft-ai"
version = "0.1.0"
description = ""
authors = [
    {name = "deon66@gmail.com"}
]
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "pytest>=8.4.1,<9.0.0",
    "pytest-cov>=4.1.0,<5.0.0",
    "torch>=2.2.0,<3.0.0",
    "scikit-learn>=1.4.0,<2.0.0",
    "xgboost>=2.0.0,<3.0.0",
    "lightgbm>=4.3.0,<5.0.0",
    "langchain>=0.1.0,<0.2.0",
    "mlflow>=2.12.0,<3.0.0",
    "pandas>=2.2.0,<3.0.0",
    "numpy>=1.26.0,<2.0.0",
    "pyspark>=3.5.0,<4.0.0",
    "kafka-python>=2.0.2,<3.0.0",
    "boto3>=1.34.0,<2.0.0",
    "pgvector>=0.2.4,<1.0.0",
    "neptune-client>=1.8.0,<2.0.0",
    "sagemaker>=2.218.0,<3.0.0",
    "docker>=7.0.0,<8.0.0",
    "kubernetes>=29.0.0,<30.0.0",
    "prometheus-client>=0.20.0,<1.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "requests>=2.31.0,<3.0.0",
    "pydantic>=2.7.0,<3.0.0"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

