# ShieldCraft AI: Sensitive Secrets for dev environment
# Only include secrets that must be stored securely in AWS Secrets Manager

secrets:
  glue_db_admin_password:
    name: shieldcraft-dev-glue-db-admin-password
    description: Glue DB admin password for dev
    generate: true
    generate_key: password

  airbyte_source_db_password:
    name: shieldcraft-dev-airbyte-source-db-password
    description: Airbyte source DB password for dev
    generate: true
    generate_key: password

  opensearch_admin_password:
    name: shieldcraft-dev-opensearch-admin-password
    description: OpenSearch admin password for dev
    generate: true
    generate_key: password

  sagemaker_model_registry_password:
    name: shieldcraft-dev-sagemaker-model-registry-password
    description: SageMaker model registry DB password for dev
    generate: true
    generate_key: password

  third_party_api_key:
    name: shieldcraft-dev-third-party-api-key
    description: API key for external service in dev
    generate: false
    template: '{"api_key": "your-key-here"}'
