# ShieldCraft AI: Sensitive Secrets for prod environment
# Only include secrets that must be stored securely in AWS Secrets Manager

secrets:
  glue_db_admin_password:
    name: shieldcraft-prod-glue-db-admin-password
    description: Glue DB admin password for prod
    generate: true
    generate_key: password

  airbyte_source_db_password:
    name: shieldcraft-prod-airbyte-source-db-password
    description: Airbyte source DB password for prod
    generate: true
    generate_key: password

  opensearch_admin_password:
    name: shieldcraft-prod-opensearch-admin-password
    description: OpenSearch admin password for prod
    generate: true
    generate_key: password

  sagemaker_model_registry_password:
    name: shieldcraft-prod-sagemaker-model-registry-password
    description: SageMaker model registry DB password for prod
    generate: true
    generate_key: password

  third_party_api_key:
    name: shieldcraft-prod-third-party-api-key
    description: API key for external service in prod
    generate: false
    template: '{"api_key": "your-key-here"}'

  kafka_scram_credentials:
    name: shieldcraft-prod-kafka-scram-credentials
    description: SASL/SCRAM credentials for external Kafka (optional; migrations/hybrid)
    generate: false
    template: '{"username": "produser", "password": "changeme"}'
