# ShieldCraft AI: Sensitive Secrets for staging environment
# Only include secrets that must be stored securely in AWS Secrets Manager

secrets:
  glue_db_admin_password:
    name: shieldcraft-staging-glue-db-admin-password
    description: Glue DB admin password for staging
    generate: true
    generate_key: password

  airbyte_source_db_password:
    name: shieldcraft-staging-airbyte-source-db-password
    description: Airbyte source DB password for staging
    generate: true
    generate_key: password

  opensearch_admin_password:
    name: shieldcraft-staging-opensearch-admin-password
    description: OpenSearch admin password for staging
    generate: true
    generate_key: password

  sagemaker_model_registry_password:
    name: shieldcraft-staging-sagemaker-model-registry-password
    description: SageMaker model registry DB password for staging
    generate: true
    generate_key: password

  third_party_api_key:
    name: shieldcraft-staging-third-party-api-key
    description: API key for external service in staging
    generate: false
    template: '{"api_key": "your-key-here"}'
