app:
  env: staging
  region: af-south-1
  resource_prefix: shieldcraft-staging

  log_level: INFO
  enable_feature_x: false

  # Cost and governance controls
  budget_limit_usd: 3000  # Monthly budget limit for staging environment
  cost_alert_thresholds:
    - 50
    - 80
    - 100
  cost_tags:
    project: shieldcraft-ai
    environment: staging
    owner: ai-solutions
  enable_cost_explorer: true
  enable_resource_tagging: true
  enable_budget_alerts: true

  buckets:
    - id: RawDataBucket
      name: shieldcraft-staging-raw
      versioned: true
      encryption: S3_MANAGED
      block_public_access: BLOCK_ALL
      removal_policy: DESTROY
    - id: ProcessedDataBucket
      name: shieldcraft-staging-processed
      versioned: true
      encryption: S3_MANAGED
      block_public_access: BLOCK_ALL
      removal_policy: DESTROY
    - id: AnalyticsDataBucket
      name: shieldcraft-staging-analytics
      versioned: true
      encryption: S3_MANAGED
      block_public_access: BLOCK_ALL
      removal_policy: DESTROY
  lifecycle_policy_days: 60
  enable_access_logs: true

glue:
  database_name: shieldcraft_staging_db
  crawler_schedule: cron(0 2 * * ? *)
  enable_data_quality: true

msk:
  security_group:
    id: MskSecurityGroup
    description: Security group for MSK brokers
    allow_all_outbound: true
  cluster:
    id: ShieldCraftMskCluster
    name: shieldcraft-msk-cluster-staging
    kafka_version: 3.5.1
    number_of_broker_nodes: 3
    instance_type: kafka.m5.large
    enhanced_monitoring: PER_TOPIC_PER_BROKER

lambda_:
  functions: []

opensearch:
  security_group:
    id: OpenSearchSecurityGroup
    description: Security group for OpenSearch
    allow_all_outbound: true
  domain:
    id: ShieldCraftOpenSearchDomain
    name: shieldcraft-opensearch-staging
    engine_version: OpenSearch_2.11
    cluster_config:
      instanceType: t3.small.search
      instanceCount: 2
    node_to_node_encryption_options:
      enabled: true
    encryption_at_rest_options:
      enabled: true
    ebs_options:
      ebsEnabled: true
      volumeSize: 20
      volumeType: gp3

airbyte:
  deployment_type: ecs
  min_task_count: 1
  max_task_count: 3

data_quality:
  dq_framework: deequ
  dq_schedule: cron(0 3 * * ? *)

lakeformation:
  admin_role: ShieldCraftLakeAdmin
  data_lake_location: s3://shieldcraft-staging-analytics
