AWSTemplateFormatVersion: "2010-09-09"
Description: ShieldCraft AI Proton EventBridge Service Template
Parameters:
  AppName:
    Type: String
    Description: Application name for tagging
  Domain:
    Type: String
    Description: Business domain for tagging
  EventBusName:
    Type: String
    Description: Name of the EventBridge bus
  RuleName:
    Type: String
    Description: Name of the EventBridge rule
  TargetArn:
    Type: String
    Description: ARN of the rule target (e.g., Lambda, StepFunction)
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Name of the Proton environment
Resources:
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref EventBusName
      Tags:
        - Key: Project
          Value: ShieldCraftAI
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
        - Key: Environment
          Value: EnvironmentName
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Ref RuleName
      EventBusName: !Ref EventBusName
      EventPattern:
        source:
          - shieldcraft.ai
      State: ENABLED
      Targets:
        - Arn: !Ref TargetArn
          Id: "Target1"
      Tags:
        - Key: Project
          Value: ShieldCraftAI
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
        - Key: Environment
          Value: EnvironmentName
Outputs:
  EventBusName:
    Description: Name of the EventBridge bus
    Value: EventBus
  EventRuleName:
    Description: Name of the EventBridge rule
    Value: EventRule
