AWSTemplateFormatVersion: "2010-09-09"
Description: ShieldCraft AI Proton Glue Service Template
Parameters:
  AppName:
    Type: String
    Description: Logical application name (e.g., ShieldCraftAI)
  Domain:
    Type: String
    Description: Functional domain (e.g., data)
  DatabaseName:
    Type: String
    Description: Name of the Glue database
  CrawlerName:
    Type: String
    Description: Name of the Glue crawler
  CrawlerRoleArn:
    Type: String
    Description: ARN of the IAM role for the crawler
  TargetPath:
    Type: String
    Description: S3 path to crawl (e.g., s3://bucket/prefix)
  EnvironmentName:
    Type: String
    Description: Name of the Proton environment
    AllowedValues:
      - dev
      - staging
      - prod
Resources:
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: !Ref DatabaseName
        Description: Glue database for ShieldCraft AI
      Tags:
        - Key: Environment
          Value: EnvironmentName
        - Key: Project
          Value: shieldcraft-ai
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref CrawlerName
      Role: !Ref CrawlerRoleArn
      DatabaseName: !Ref DatabaseName
      Targets:
        S3Targets:
          - Path: !Ref TargetPath
      Tags:
        - Key: Environment
          Value: EnvironmentName
        - Key: Project
          Value: shieldcraft-ai
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
Outputs:
  GlueDatabaseName:
    Description: Name of the Glue database
    Value: !Ref GlueDatabase
  GlueCrawlerName:
    Description: Name of the Glue crawler
    Value: !Ref GlueCrawler
