AWSTemplateFormatVersion: "2010-09-09"
Description: ShieldCraft AI Proton Lake Formation Service Template
Parameters:
  AppName:
    Type: String
    Description: Application name for tagging
  Domain:
    Type: String
    Description: Business domain for tagging
  DataLakeAdmins:
    Type: List<String>
    Description: List of IAM ARNs for Lake Formation admins
  DatabaseName:
    Type: String
    Description: Name of the Glue database to register
  S3Location:
    Type: String
    Description: S3 path for the data lake (e.g., s3://bucket/prefix)
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Name of the Proton environment
Resources:
  LakeFormationDataLakeSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins: !Ref DataLakeAdmins
  LakeFormationResource:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn: !Ref S3Location
      UseServiceLinkedRole: true
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: !Ref DatabaseName
        Description: Lake Formation database for ShieldCraft AI
      Tags:
        - Key: Project
          Value: ShieldCraftAI
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
        - Key: Environment
          Value: EnvironmentName
Outputs:
  LakeFormationAdmins:
    Description: List of Lake Formation admin ARNs
    Value: !Ref DataLakeAdmins
  LakeFormationResourceArn:
    Description: Registered S3 resource ARN
    Value: !GetAtt LakeFormationResource.ResourceArn
  GlueDatabaseName:
    Description: Name of the Glue database
    Value: !Ref GlueDatabase
