AWSTemplateFormatVersion: "2010-09-09"
Description: ShieldCraft AI Proton OpenSearch Service Template
Parameters:
  AppName:
    Type: String
    Description: Logical application name (e.g., ShieldCraftAI)
  Domain:
    Type: String
    Description: Functional domain (e.g., analytics_search)
  DomainName:
    Type: String
    Description: Name of the OpenSearch domain
  InstanceType:
    Type: String
    Description: EC2 instance type for OpenSearch nodes
    Default: t3.small.search
  InstanceCount:
    Type: Number
    Description: Number of OpenSearch nodes
    Default: 2
  ExistingSecretArn:
    Type: String
    Description: Optional ARN of an existing admin credential secret for the domain
  EnvironmentName:
    Type: String
    Description: Name of the Proton environment
    AllowedValues:
      - dev
      - staging
      - prod
Resources:
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Sub "${DomainName}-${EnvironmentName}"
      EngineVersion: "OpenSearch_2.11"
      ClusterConfig:
        InstanceType: !Ref InstanceType
        InstanceCount: !Ref InstanceCount
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 20
        VolumeType: gp3
      NodeToNodeEncryptionOptions:
        Enabled: true
      EncryptionAtRestOptions:
        Enabled: true
      Tags:
        - Key: Environment
          Value: EnvironmentName
        - Key: Project
          Value: shieldcraft-ai
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
Outputs:
  OpenSearchDomainName:
    Description: Name of the OpenSearch domain
    Value: OpenSearchDomain
  DomainAdminSecretArn:
    Description: Existing admin secret ARN for the domain (if provided)
    Value: ExistingSecretArn
