AWSTemplateFormatVersion: "2010-09-09"
Description: ShieldCraft AI Proton SageMaker Service Template
Parameters:
  AppName:
    Type: String
    Description: Application name for tagging
  Domain:
    Type: String
    Description: Business domain for tagging
  EndpointName:
    Type: String
    Description: Name of the SageMaker endpoint
  ModelName:
    Type: String
    Description: Name of the SageMaker model
  InstanceType:
    Type: String
    Description: EC2 instance type for endpoint
    Default: ml.m5.large
  VaultSecretArn:
    Type: String
    Description: ARN of the imported vault secret
  ExecutionRoleArn:
    Type: String
    Description: ARN of the SageMaker execution role
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Name of the Proton environment
Resources:
  SageMakerModel:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: !Ref ModelName
      PrimaryContainer:
        Image: public.ecr.aws/sagemaker/model:latest
        ModelDataUrl: s3://bucket/model.tar.gz
      ExecutionRoleArn: !Ref ExecutionRoleArn
      Tags:
        - Key: Project
          Value: ShieldCraftAI
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
        - Key: Environment
          Value: EnvironmentName
  SageMakerEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      EndpointConfigName: !Ref EndpointName
      ProductionVariants:
        - VariantName: "AllTraffic"
          ModelName: !Ref ModelName
          InitialInstanceCount: 1
          InstanceType: !Ref InstanceType
      Tags:
        - Key: Project
          Value: ShieldCraftAI
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
        - Key: Environment
          Value: EnvironmentName
  SageMakerEndpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName: !Ref EndpointName
      EndpointConfigName: !Ref EndpointName
      Tags:
        - Key: Project
          Value: ShieldCraftAI
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
        - Key: Environment
          Value: EnvironmentName
  VaultSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref EndpointName
      Description: SageMaker endpoint secret
      SecretString: !Ref VaultSecretArn
      Tags:
        - Key: Project
          Value: ShieldCraftAI
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
        - Key: Environment
          Value: EnvironmentName
Outputs:
  SageMakerEndpointName:
    Description: Name of the SageMaker endpoint
    Value: !Ref SageMakerEndpoint
  SageMakerModelName:
    Description: Name of the SageMaker model
    Value: !Ref SageMakerModel
  VaultSecretArn:
    Description: ARN of the imported vault secret
    Value: !Ref VaultSecret
