AWSTemplateFormatVersion: "2010-09-09"
Description: ShieldCraft AI Proton Step Functions Service Template
Parameters:
  AppName:
    Type: String
    Description: Application name for tagging
  Domain:
    Type: String
    Description: Business domain for tagging
  StateMachineName:
    Type: String
    Description: Name of the Step Functions state machine
  DefinitionString:
    Type: String
    Description: JSON definition of the state machine
  RoleArn:
    Type: String
    Description: ARN of the IAM role for Step Functions
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Name of the Proton environment
Resources:
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${StateMachineName}-${EnvironmentName}"
      DefinitionString: !Ref DefinitionString
      RoleArn: !Ref RoleArn
      Tags:
        - Key: Project
          Value: ShieldCraftAI
        - Key: App
          Value: !Ref AppName
        - Key: Domain
          Value: !Ref Domain
        - Key: Env
          Value: !Ref EnvironmentName
        - Key: Environment
          Value: EnvironmentName
Outputs:
  StateMachineName:
    Description: Name of the Step Functions state machine
    Value: !Ref StateMachine
  RoleArn:
    Description: ARN of the IAM role for Step Functions
    Value: !Ref RoleArn
