# Ensure Docker is available in CI before any Docker build/scan steps
---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  flow_commit:
    name: "Nox Orchestration: flow_commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.AWS_PROFILE_NAME }}" ] || [ -z "${{ secrets.AWS_DEFAULT_REGION }}" ]; then
            echo "Missing required secrets: AWS_PROFILE_NAME or AWS_DEFAULT_REGION"; exit 1
          fi
      - name: Aggressive disk cleanup (pre-deps)
        run: |
          echo "::group::DISK_DEBUG: Aggressive disk cleanup (pre-deps)"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost
          sudo rm -rf /opt/hostedtoolcache/CodeQL /opt/hostedtoolcache/go /usr/local/share/powershell
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo apt-get clean
          docker system prune -af --volumes
          docker builder prune -af
          poetry cache clear --all pypi || true
          pip cache purge || true
          rm -rf .pytest_cache .nox dist build __pycache__ *.pyc *.pyo
          echo "DISK_DEBUG: df -h after cleanup"
          df -h
          echo "DISK_DEBUG: du -sh workspace root"
          du -sh ./*
          echo "::endgroup::"
      - name: Clean Python/Nox artifacts (pre-Nox)
        run: |
          echo "::group::DISK_DEBUG: Clean Python/Nox artifacts (pre-Nox)"
          rm -rf .pytest_cache .nox dist build __pycache__ *.pyc *.pyo
          poetry cache clear --all pypi || true
          pip cache purge || true
          echo "DISK_DEBUG: df -h after Python/Nox artifact cleanup"
          df -h
          echo "DISK_DEBUG: du -sh workspace root"
          du -sh ./*
          echo "::endgroup::"
      - name: Read Python version from .python-version
        id: python_version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache Poetry and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
            ~/.virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-py${{ env.PYTHON_VERSION }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Poetry
        run: pip install poetry
      - name: Install project dependencies (main only)
        run: |
          echo "::group::DISK_DEBUG: Install project dependencies (main only)"
          poetry install --with dev --no-interaction --no-root
          poetry cache clear --all pypi || true
          pip cache purge || true
          echo "DISK_DEBUG: df -h after poetry install"
          df -h
          echo "DISK_DEBUG: du -sh workspace root"
          du -sh ./*
          echo "::endgroup::"
      - name: Run all checks via Nox (flow_commit)
        run: |
          echo "::group::DISK_DEBUG: Run all checks via Nox (flow_commit)"
          export PYTHONPATH=$(pwd)
          poetry run nox -s commit_flow
          poetry cache clear --all pypi || true
          pip cache purge || true
          echo "DISK_DEBUG: df -h after Nox checks"
          df -h
          echo "DISK_DEBUG: du -sh workspace root"
          du -sh ./*
          echo "::endgroup::"
      - name: Aggressive disk cleanup (post-Nox)
        run: |
          echo "::group::DISK_DEBUG: Aggressive disk cleanup (post-Nox)"
          rm -rf .pytest_cache .nox dist build __pycache__ *.pyc *.pyo
          poetry cache clear --all pypi || true
          pip cache purge || true
          docker system prune -af --volumes
          docker builder prune -af
          echo "DISK_DEBUG: df -h after post-Nox cleanup"
          df -h
          echo "DISK_DEBUG: du -sh workspace root"
          du -sh ./*
          echo "::endgroup::"

  cdk_deploy:
    name: "CDK Deploy"
    runs-on: ubuntu-latest
    needs: [flow_commit]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Read Python version from .python-version
        id: python_version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        run: pip install poetry
      - name: Install project dependencies
        run: poetry install --no-interaction --no-root --with dev
      - name: Configure AWS credentials (OIDC, Identity Center)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1
      - name: Install AWS CDK CLI (v2)
        run: npm install -g aws-cdk
      - name: CDK Synthesis (Validation)
        run: cdk synth
      - name: Deploy AWS CDK stacks via Nox
        env:
          AWS_PROFILE: ${{ secrets.AWS_PROFILE_NAME }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: poetry run nox -s cdk_deploy

  docker_build_api:
    name: "Docker Build: API"
    runs-on: ubuntu-latest
    needs: [flow_commit]
    if: >
      github.event_name == 'push' || github.event_name == 'pull_request'
      && (
        contains(github.event.head_commit.message, 'Dockerfile.api') ||
        contains(github.event.head_commit.message, 'src/') ||
        contains(github.event.head_commit.message, 'pyproject.toml') ||
        contains(github.event.head_commit.message, 'poetry.lock')
      )
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set image tag
        id: meta
        run: echo "image_tag=ghcr.io/${{ github.repository_owner,, }}/shieldcraft-api:${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push with BuildKit cache (API)
        uses: docker/build-push-action@v5
        with:
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          context: .
          file: Dockerfile.api
          target: final
          push: true
          tags: ${{ steps.meta.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/amd64
            linux/arm64
      - name: Export image tag
        id: export_tag
        run: echo "image_tag=${{ steps.meta.outputs.image_tag }}" >> $GITHUB_ENV
      - name: Aggressive Docker Cleanup
        run: |
          docker system prune -af --volumes
          docker builder prune -af
          df -h

  docker_build_ingestion:
    name: "Docker Build: Ingestion"
    runs-on: ubuntu-latest
    needs: [flow_commit]
    if: >
      github.event_name == 'push' || github.event_name == 'pull_request'
      && (
        contains(github.event.head_commit.message, 'Dockerfile.ingestion') ||
        contains(github.event.head_commit.message, 'src/') ||
        contains(github.event.head_commit.message, 'pyproject.toml') ||
        contains(github.event.head_commit.message, 'poetry.lock')
      )
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set image tag
        id: meta
        run: echo "image_tag=ghcr.io/${{ github.repository_owner,, }}/shieldcraft-ingestion:${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push with BuildKit cache (Ingestion)
        uses: docker/build-push-action@v5
        with:
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          context: .
          file: Dockerfile.ingestion
          target: final
          push: true
          tags: ${{ steps.meta.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/amd64
            linux/arm64
      - name: Export image tag
        id: export_tag
        run: echo "image_tag=${{ steps.meta.outputs.image_tag }}" >> $GITHUB_ENV
      - name: Aggressive Docker Cleanup
        run: |
          docker system prune -af --volumes
          docker builder prune -af
          df -h

  docker_build_main:
    name: "Docker Build: Main"
    runs-on: ubuntu-latest
    needs: [flow_commit]
    if: >
      github.event_name == 'push' || github.event_name == 'pull_request'
      && (
        contains(github.event.head_commit.message, 'Dockerfile') ||
        contains(github.event.head_commit.message, 'src/') ||
        contains(github.event.head_commit.message, 'pyproject.toml') ||
        contains(github.event.head_commit.message, 'poetry.lock')
      )
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set image tag
        id: meta
        run: echo "image_tag=ghcr.io/${{ github.repository_owner,, }}/shieldcraft-main:${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push with BuildKit cache (Main)
        uses: docker/build-push-action@v5
        with:
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          context: .
          file: Dockerfile
          target: final
          push: true
          tags: ${{ steps.meta.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/amd64
            linux/arm64
      - name: Export image tag
        id: export_tag
        run: echo "image_tag=${{ steps.meta.outputs.image_tag }}" >> $GITHUB_ENV
      - name: Aggressive Docker Cleanup
        run: |
          docker system prune -af --volumes
          docker builder prune -af
          df -h

  docker_scan_api:
    name: "Docker Scan: API"
    runs-on: ubuntu-latest
    needs: [docker_build_api]
    steps:
      - uses: actions/checkout@v4
      - name: Pull built image
        run: |
          docker pull "$IMAGE_TAG"
      - name: Docker Scan (API)
        run: |
          docker pull aquasec/trivy:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image "$IMAGE_TAG"
          docker pull anchore/grype:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            anchore/grype:latest "$IMAGE_TAG"

  docker_scan_ingestion:
    name: "Docker Scan: Ingestion"
    runs-on: ubuntu-latest
    needs: [docker_build_ingestion]
    steps:
      - uses: actions/checkout@v4
      - name: Pull built image
        run: |
          docker pull "$IMAGE_TAG"
      - name: Docker Scan (Ingestion)
        run: |
          docker pull aquasec/trivy:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image "$IMAGE_TAG"
          docker pull anchore/grype:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            anchore/grype:latest "$IMAGE_TAG"

  docker_scan_main:
    name: "Docker Scan: Main"
    runs-on: ubuntu-latest
    needs: [docker_build_main]
    steps:
      - uses: actions/checkout@v4
      - name: Pull built image
        run: |
          docker pull "$IMAGE_TAG"
      - name: Docker Scan (Main)
        run: |
          docker pull aquasec/trivy:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image "$IMAGE_TAG"
          docker pull anchore/grype:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            anchore/grype:latest "$IMAGE_TAG"

# Fail fast: if any job fails, the workflow stops (default in GitHub Actions unless using a matrix with fail-fast: false)
